[package]
name = "unit_system"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unit_derive = {version="0.0.1", path="../unit_derive"}
